---
title: "Plosives results (plosion index)"
author: "Florent Dueme"
date: "30/11/2021"
output: html_document
---

This is a Markdown document to present the results of the plosive (plosioin index) part of the FrSpBil experiment.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Sys.setenv(LANG = "en") # Set error language to English
library(tidyverse)
library(ggplot2)
library(lme4)
library(emmeans)
library(rstatix) # Function rstatix::convert_as_factor
library(MASS) # Function MASS::fractions
library(sjPlot) # Function sjPlot::tab_model
```


```{r load_data, include=FALSE}
data = as.data.frame(read.csv("all_data_burst_24_01_2022.csv", sep=";"),header=T,sep=";",dec=".")

data$Plosion_index = as.numeric(data$Plosion_index)
data$VOT = as.numeric(data$VOT)
data$Length = as.numeric(data$Length)

str(data)
```



```{r Prepare_data, include=FALSE}

# Separate data by language
french <- data[data$Language=="French",]
spanish <- data[data$Language=="Spanish",]


# Make factors
french <- french %>% convert_as_factor(Speaker, Gender, Group, Task, Grapheme, Word)
french$Group <- relevel(french$Group, 'Monolinguals')
french$Grapheme <- relevel(french$Grapheme, 'b')

spanish <- spanish %>% convert_as_factor(Speaker, Gender, Group, Task, Grapheme, Word)
spanish$Group <- relevel(spanish$Group, 'Monolinguals')
spanish$Grapheme <- relevel(spanish$Grapheme, 'b')


str(french)
str(spanish)
```

```{r Contrasts, include=FALSE}

# Create contrasts
F_VS_M <- c(-1, 1)
Mono_VS_Bi <- c(-1, 1)
b_VS_v <- c(-1, 1)

contrasts(french$Gender) <- F_VS_M
contrasts(french$Group) <- Mono_VS_Bi
contrasts(french$Grapheme) <- b_VS_v

contrasts(spanish$Gender) <- F_VS_M
contrasts(spanish$Group) <- Mono_VS_Bi
contrasts(spanish$Grapheme) <- b_VS_v

# Custom contrast for task
Contrasts <- rbind(
  Naming_Vs_Reading = c(name=2, PW=-1, read=-1),
  Word_VS_PW = c(name=0, PW=1, read=-1)
) 

# fractions(t(Contrasts))

# Function to calculate general inverse
ginv2 <- function(x)
  fractions(provideDimnames(ginv(x),
                            base=dimnames(x)[2:1]))


contrast_mat <- ginv2(Contrasts)

# contrast_mat

```



```{r French_model}

# The full model fails to converge
PI_f_no_convergence <-lmer(log(Plosion_index) ~ Group*Grapheme*Task + Gender + (Grapheme|Speaker) + (Group|Word), data = french, 
                           contrasts = list(Task = contr.sum(3)), control=lmerControl(optCtrl=list(maxfun=50000), optimizer="bobyqa"))

# After removing the interactions involving Task and some of the random slopes, the model does converge
# PI_f <-lmer(log(Plosion_index) ~ Group*Grapheme + Gender + Task + (Grapheme|Speaker) + (1|Word), data = french,
#             contrasts = list(Task=contrast_mat))

summary(PI_f_no_convergence)

tab_model(PI_f_no_convergence)
```


```{r}
anova(PI_f, PI_f_no_convergence)
```



```{r Spanish_model}

PI_s <-lmer(log(Plosion_index) ~ Group*Grapheme*Task + Gender + (Grapheme|Speaker) + (1|Word), data = spanish,
contrasts = list(Task=contrast_mat))

# PI_s <-lmer(log(Plosion_index) ~ Group*Grapheme + Task + Gender + (Grapheme|Speaker) + (Group|Word), data = spanish,
#             contrasts = list(Task=contrast_mat))
           
summary(PI_s)

tab_model(PI_s)

```


```{r Spanish_plo_model}

# Now using only the tokens not produced as fricatives

spanish_plo <- spanish[spanish$Burst == 1,]

PI_s_plo <-lmer(log(Plosion_index) ~ Group*Grapheme + Gender + Task + (Grapheme|Speaker) + (Group|Word), data = spanish_plo)

tab_model(PI_s_plo)

```


```{r Spanish_burst}

xtabs( ~ Group + Grapheme + Burst, data=data)

logistic <- glm(Burst ~ Group*Grapheme, data=spanish, family="binomial")
summary(logistic)

```




